# Generated by Django 5.0.6 on 2024-06-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='item_price',
            new_name='initial_bid',
        ),
    ]
