# Generated by Django 5.0.6 on 2024-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_item_price_listing_initial_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Description missing', max_length=300),
        ),
    ]
