# Generated by Django 5.0.6 on 2024-06-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Category missing', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.TextField(default='Image link missing', max_length=150),
        ),
    ]
