# Generated by Django 5.0.6 on 2024-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health'), ('toys', 'Toys'), ('home', 'Home')], default='Select category', max_length=50),
        ),
    ]
