# Generated by Django 5.0.6 on 2024-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(default='Image link missing', max_length=50),
        ),
    ]
