# Generated by Django 5.0.6 on 2024-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('select', 'Select'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health'), ('toys', 'Toys'), ('home', 'Home'), ('jewelry', 'Jewelry')], default='Add category', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Add description', max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(default="Add a link to your product's image", max_length=50),
        ),
    ]
