# Generated by Django 5.0.6 on 2024-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health'), ('toys', 'Toys'), ('home', 'Home'), ('jewelry', 'Jewelry')], default='Add category', max_length=50),
        ),
    ]
