# Generated by Django 5.0.6 on 2024-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
