# Generated by Django 5.0.6 on 2024-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='initial_bid',
            new_name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health'), ('toys', 'Toys'), ('home', 'Home'), ('jewelry', 'Jewelry'), ('automobiles', 'Automobiles')], default='Add category', max_length=50),
        ),
    ]
