# Generated by Django 5.0.6 on 2024-06-20 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_initial_bid_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_values', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='placed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
