# Generated by Django 5.0.6 on 2024-06-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid_bid_value_bid_placed_by_bid_placed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
