# Generated by Django 5.0.6 on 2024-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Health', 'Health'), ('Toys', 'Toys'), ('Home', 'Home'), ('Jewelry', 'Jewelry'), ('automobiles', 'Automobiles'), ('Luxury', 'Luxury')], default='Add category', max_length=50),
        ),
    ]
