# Generated by Django 5.0.6 on 2024-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('Electronics', 'Electronics'), ('health', 'Health'), ('Toys', 'Toys'), ('Home', 'Home'), ('jewelry', 'Jewelry'), ('Automobiles', 'Automobiles'), ('luxury', 'Luxury')], default='Add category', max_length=50),
        ),
    ]
