# Generated by Django 5.0.6 on 2024-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
