# Generated by Django 5.0.6 on 2024-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_rename_item_name_listing_item_comment_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Add comment here', max_length=300),
        ),
    ]
