# Generated by Django 5.0.6 on 2024-06-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='item',
        ),
    ]
